"""diary entry pin

Revision ID: 5432f731dc5d
Revises: 90bc82285643
Create Date: 2026-06-02 15:57:48.170138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5432f731dc5d'
down_revision: Union[str, Sequence[str], None] = '90bc82285643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_entry', sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_entry', 'pinned')
    # ### end Alembic commands ###
