"""diary entry tags

Revision ID: 90bc82285643
Revises: 
Create Date: 2026-06-02 15:27:54.365396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bc82285643'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_entry', sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'), )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_entry', 'tags')
    # ### end Alembic commands ###
